export enum Color {
  Primary = "var(--color-secondary)",
  PrimaryDark = "var(--color-primaryDark)",
  Secondary = "var(--color-secondary)",
  White = "var(--color-white)",
  Gray = "var(--color-gray)",
  Light = "var(--color-light)",
  Red = "var(--color-red)",
  Blue = "var(--color-blue)",
  Green = "var(--color-green)",
  Orange = "var(--color-orange)",
  Purple = "var(--color-purple)",
  Black = "var(--color-black)",
  Backround = "var(--color-dark)",
}
